### ISSUE TITLE
attempting to create a wallet with an invalid password returns an unrelated error

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#21]
POST to `api/lnd/wallet`:
```
{
	"alias": "alice",
	"password": "al"
}
```

console logs:
initWallet Error: 2 UNKNOWN: password must have at least 8 characters

API returns http code 500 with json data:

```
{
  "field": "health",
  "message": "LND is down",
  "success": false
}
```

**Comment by Emad-salah** [comment]
I've made the error messages for the auth route the same as the one in the logs but I've removed the "UNKNOWN: " part so it's clearer on your end. 2e187339179a61f5918cc65400bbdbe77ecdf778
