### ISSUE TITLE
unhandled typerror in src/routes.js:255:18

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#22]
https://github.com/jhizzle84/api/blob/7faa3a1a43e7798428a9bed6fa61435c09fd9554/src/routes.js#L255

```
TypeError: req.status is not a function
    at /home/daniel/workspace/api/src/routes.js:255:18

```

I think it should actually be `return res.status(400) // ...`

**Comment by Emad-salah** [comment]
This typo is fixed and pushed to the master branch now! 😄 0010613a5e13c8a51b961e9ac7ecd553e9542a5b
