### ISSUE TITLE
create an unified balance endpoint

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#27]
Create an unified balance endpoint that pulls info from `pendingChannels` and `getInfo` to serve an `unconfirmed_balance`.

**Comment by danlugo92** [comment]
alternatively update the current `balance` endpoint

**Comment by jhizzle84** [comment]
note this should only reflect the local amount of pending channels, I think it best to keep balance and unconfirmed_balance separate so we can check to see if unconfirmed_balance is null
