### ISSUE TITLE
unexpected lnd crash

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#28]
:12:57 -0430 -0430)
panic: couldn't write cfheaders msg: attempt to write cfheaders out of order! Tip=aa89fa2bd26065c4bd59aa183c613510ef82c111eb0fa544699a1de537c29838 (height=780000), prev_hash=07d368f31ee9af7468dcf3e2a483502c536f395d348869cf1ca3c48b2604c6d4.

goroutine 10 [running]:
github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0xc0000c85a0, 0x2111520, 0xc0016a60f0, 0x21112e0, 0xc0017a8d20, 0xab1c5ed5923f8201)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:1051 +0xe2f
github.com/lightninglabs/neutrino.queryChainServiceBatch(0xc0000e2280, 0xc00025e840, 0x4, 0x4, 0xc00236e420, 0xc0000844e0, 0x0, 0x0, 0x0)
	github.com/lightninglabs/neutrino@v0.10.0/query.go:569 +0x94f
github.com/lightninglabs/neutrino.NewChainService.func3(0xc00025e840, 0x4, 0x4, 0xc00236e420, 0xc0000844e0, 0x0, 0x0, 0x0)
	github.com/lightninglabs/neutrino@v0.10.0/neutrino.go:674 +0x83
github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0xc000200340, 0xc001aa4000, 0x30c, 0x400, 0xc0000a60c0, 0x300)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:916 +0x822
github.com/lightninglabs/neutrino.(*blockManager).cfHandler(0xc000200340)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:623 +0xd79
github.com/lightninglabs/neutrino.(*blockManager).Start.func1(0xc000200340)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:312 +0x1d9
created by github.com/lightninglabs/neutrino.(*blockManager).Start
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:298 +0xfb

**Comment by jhizzle84** [comment]
Lnd issues to https://github.com/lightningnetwork/lnd
