### ISSUE TITLE
api/lnd/balance returns strings instead of numbers

### ISSUE THREAD

**Issue by danlugo92** [jhizzle84/api#6]
`{
  "total_balance": "0",
  "confirmed_balance": "0",
  "unconfirmed_balance": "0"
}`

**Comment by Emad-salah** [comment]
I've checked this issue out and I guess they're using strings for numbers just because of the float precision issue that's on JavaScript where floats aren't represented accurately. You might have to use (BigNumber)[https://github.com/MikeMcl/bignumber.js] lib in order to deal with those numbers
