### ISSUE TITLE
add cluster/multi-threading

### ISSUE THREAD

**Issue by jhizzle84** [jhizzle84/api#72]
performance is pretty bad, implement multi-threading

**Comment by jhizzle84** [comment]
https://millermedeiros.github.io/mdoc/examples/node_api/doc/cluster.html

**Comment by Emad-salah** [comment]
I believe the main issue behind the slow performance is due to the use of a lot of synchronous functions that block the main thread. I'll be creating a separate branch in which I will be replacing the sync functions with their async counterparts.
